Feature/video
WP-Brothers/allegion pull request #10
Opened 2024-01-03 13:17 UTC by SBtimvanandel

2024-01-17 08:15 UTC, guid-ooo requested changes

2024-01-17 08:15 UTC, guid-ooo commented on wp-content/themes/socialbrothers/templates/blocks/video-old/block.json
> +  "name": "acf/video-old",
video-old?

2024-01-17 15:01 UTC, norayesnir commented on wp-content/themes/socialbrothers/templates/blocks/video-old/block.json
> +  "name": "acf/video-old",
Video old was kept just in case 
> commit: 4c0207c

2024-01-18 10:01 UTC, guid-ooo approved these changes

2024-01-18 10:01 UTC, merged